services:
  mutasi-hub:
    image: ghcr.io/hirumakuncoro/mutasi-hub:latest
    restart: unless-stopped
    env_file:
      - .env
    stop_grace_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mutasi-hub.rule=Host(`mutasi.duitebot.com`)"
      - "traefik.http.routers.mutasi-hub.entrypoints=websecure"
      - "traefik.http.routers.mutasi-hub.tls.certresolver=cfresolver"
      - "traefik.http.services.mutasi-hub.loadbalancer.server.port=3000"